In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
from sklearn.linear_model import Ridge

In [3]:
np.random.seed(42)
X = np.random.rand(100,5)
y = X@np.array([1.5,-2.0,1.0,0.5,2.0]) + np.random.randn(100)

In [4]:
X

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998],
       [0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203],
       [0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249],
       [0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998],
       [0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446],
       [0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998],
       [0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033],
       [0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451],
       [0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694],
       [0.77224477, 0.19871568, 0.

In [5]:
y

array([ 0.34549801,  4.5768742 ,  0.34374301,  0.41290584,  1.12784249,
        2.1736781 ,  1.72079425,  3.75492086,  1.37875234,  1.06431769,
        0.77368934,  3.42895589,  1.49476122,  4.58325816,  0.99347565,
       -0.56338933,  1.03794443,  1.10113691,  0.88619433,  0.9741111 ,
        0.0904768 ,  0.43470305,  2.83304559,  1.92581961,  0.95949227,
       -0.23430869,  0.82227907,  3.5532979 ,  2.48978901, -0.82657346,
        4.79534918,  1.47135753,  1.54835681,  2.06760406,  4.95960534,
        1.76515724,  1.91493489,  1.6308333 ,  0.88562695,  3.34093913,
        1.65360801,  1.48455262,  2.68618913,  0.71608942, -0.52551898,
       -1.51787057,  1.13118464,  1.94094918,  2.13604475,  3.76468805,
        2.64867659, -1.24179574, -0.60698431,  1.13098709,  2.32425779,
        1.71552204,  0.1707098 ,  0.90117912, -0.0765986 ,  0.61101153,
        1.6929443 ,  0.75351171,  2.16631264, -0.08115946,  2.04186394,
        2.27026235, -1.80302416, -0.00936835,  0.44735982,  0.34

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
ridge_reg = Ridge(alpha=1.0)
ridge_reg.fit(X_train,y_train)

Ridge()

In [8]:
y_pred_ridge = ridge_reg.predict(X_test)

In [9]:
mse_ridge = mean_squared_error(y_test,y_pred_ridge)

In [10]:
mse_ridge

np.float64(1.0278537957182399)

In [11]:
ridge_reg.coef_

array([ 0.99497892, -1.98141918,  1.38609255,  0.58735243,  1.39268583])

In [12]:
from sklearn.linear_model import Lasso

In [13]:
lasso_reg = Lasso(alpha=1.0)

In [14]:
lasso_reg.fit(X_train,y_train)

Lasso()

In [15]:
lasso_reg.coef_

array([ 0., -0.,  0.,  0.,  0.])

In [16]:
mse_lasso = mean_squared_error(y_test,lasso_reg.predict(X_test))

In [17]:
mse_lasso

np.float64(2.317321879368061)

In [18]:
from sklearn.linear_model import ElasticNet

In [19]:
elasticNet_reg = ElasticNet(alpha=1.0,l1_ratio=0.5)
elasticNet_reg.fit(X_train,y_train)

ElasticNet()

In [20]:
elasticNet_reg.coef_

array([ 0., -0.,  0.,  0.,  0.])

In [21]:
mse_elastic = mean_squared_error(y_test,elasticNet_reg.predict(X_test))

In [22]:
mse_elastic

np.float64(2.317321879368061)